spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/games-payment
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver

  kafka:
    consumer:
      bootstrap-servers: 127.0.0.1:9092
      auto-offset-reset: earliest
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer

server:
  port: 8081
